version: "3.7"
services:
  dashboard:
    build: dashboard
    image: nockio:dashboard
    volumes:
      - "/var/lib/nockio/git:/var/lib/nockio/git"
      - "/var/lib/nockio/proxy:/var/lib/nockio/proxy"
    ports:
      - "8080:80"
    networks:
      infrastructure:
        aliases:
          - "dashboard"

  git:
    build: git
    image: nockio:git
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/nockio/git:/var/lib/nockio/git"
    ports:
      - "22:22"
    networks:
      infrastructure:
        aliases:
          - "git"

  proxy:
    build: proxy
    image: nockio:proxy
    networks:
      - infrastructure
      - applications

networks:
  infrastructure:
    driver: bridge
  applications:
    driver: bridge