#!/usr/bin/env bash

# This script runs on installation.
#
# It creates a docker network, and allows containers to access the socket.

docker network create proxy --driver bridge

chmod 777 /var/run/docker.sock