#!/bin/bash

# This hook script is used to deploy an application on Nockio.
#
# This hook is loaded by default.

# Build the application
echo "Nockio: Building Application"
docker-compose --file ../.compose.nockio up --build --detach --no-color 1> ../.log.compose.nockio

# Restart the proxy
echo "Nockio: Restarting Proxy"
curl --silent --unix-socket /var/run/docker.sock --request POST http://localhost/containers/proxy/restart 1> /dev/null